separate wielder skills into "skills" and "startingskills"
lmachens/soc.gg pull request #56
Opened 2022-07-12 11:55 UTC by Unei95

- `convert.mjs` now separates skills into `startingSkills` and `skills`
- added `WielderDTO.startingSkills` field
- render startingSkills in own table in pages/wielders/[type].tsx
- removed "Command" from `WielderStats.tsx` since it's shown in the startingSkills

2022-07-12 12:28 UTC, lmachens requested changes
\^o^/
Good quality pull request!

It looks like you converted not the most recent Songs of Conquest assets.
Could you update SoC and run the extractor again?

2022-07-12 12:28 UTC, lmachens commented on pages/wielders/[type].tsx
> +    startingSkills: getSiteTerm("StartingSkills", locale),
I think you could remove L:208 (I can't add a line-comment there) :
`command: getTerm("Commanders/Details/CommanderStat/Command", locale),`

2022-07-12 12:39 UTC, Unei95 commented on pages/wielders/[type].tsx
> +                        { }
resolved in 79b2bd13ed1c75214464a55911125107442703da

2022-07-12 13:14 UTC, Unei95 commented
i forgot to run assetRipper prior to running the extractor

![facepalm](https://media.giphy.com/media/TJawtKM6OCKkvwCIqX/giphy.gif)

2022-07-13 04:57 UTC, lmachens approved these changes
Good job!
For some reason, the binary data of GOG images are different from the Steam images (or is it related to Linux?).  I pushed the steam images, because they didn't change.

2022-07-13 04:57 UTC, merged